name: C/C++ CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build_linux:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: Upload a Build Artifact
    - uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: wrk-linux
        # A file, directory or wildcard pattern that describes what to upload
        path: wrk
  build_macos:

    runs-on: macos-10.14

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: make
    - name: Upload a Build Artifact
    - uses: actions/upload-artifact@v2
      with:
        # Artifact name
        name: wrk-macos
        # A file, directory or wildcard pattern that describes what to upload
        path: wrk
